# Generated by Django 5.1.3 on 2024-12-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
