# Generated by Django 5.1.6 on 2025-05-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
