# Generated by Django 5.1.3 on 2024-12-06 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='crust',
            name='type',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pizza_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
    ]
