# Generated by Django 5.1.6 on 2025-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartitem_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the pizza.', null=True),
        ),
    ]
