# Generated by Django 5.1.3 on 2024-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartitem_pizza_name_alter_crust_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crust',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pizza_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
