# Generated by Django 5.1.3 on 2024-12-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_pizza_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image_path',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
    ]
